#pragma once

namespace Engine
{
	enum LEVEL { LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_END };

	enum UITYPE { UI_GUAGE, UI_WINDOW, UI_IMAGE, UI_BACKGROUND, UI_END };

	enum OBJECT_ID { ID_PLAYER, ID_MONSTER, ID_ENVIRONMENT, ID_INSTALLATLON, ID_WEAPON, ID_PEEKING, ID_EFFECT, ID_SKY, ID_UI, ID_END };

	enum COLLIDERTYPE { COLLTYPE_AABB, COLLTYPE_OBB, COLLTYPE_SPHERE, COLLTYPE_SPHERE_TARGET,  COLLTYPE_END };

	enum TYPE { TYPE_AABB, TYPE_OBB, TYPE_SPHERE, TYPE_SPHERE_TARGET, TYPE_END };
	
	enum COLLIDER { COLLIDER_HIT, COLLIDER_SWORD, COLLIDER_END };


	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };





}